export enum CSubtitleLanguage {
	"Bengali" = "bn",
	"English" = "en",
	"French" = "fr",
	"Spanish" = "es",
	"Arabic" = "ar",
	"Mandarin" = "cmn",
	"Russian" = "ru",
	"Portuguese" = "pt",
	"German" = "de",
	"Japanese" = "ja",
	"Hindi" = "hi",
	"Malay" = "ms",
	"Persian" = "fa",
	"Swahili" = "sw",
	"Tamil" = "ta",
	"Italian" = "it",
	"Dutch" = "nl",
	"Turkish" = "tr",
	"Vietnamese" = "vi",
	"Polish" = "pl",
	"Javanese" = "jv",
	"Punjabi" = "pa",
	"Thai" = "th",
	"Korean" = "ko"
}