export enum CSubtitleLanguage {
	"Bengali" = "ben",
	"English" = "eng",
	"French" = "fre",
	"Spanish" = "spa",
	"Arabic" = "ara",
	"Mandarin" = "cmn",
	"Russian" = "rus",
	"Portuguese" = "por",
	"German" = "deu",
	"Japanese" = "jpn",
	"Hindi" = "hin",
	"Malay" = "mal",
	"Persian" = "fas",
	"Swahili" = "swa",
	"Tamil" = "tam",
	"Italian" = "ita",
	"Dutch" = "nld",
	"Turkish" = "tur",
	"Vietnamese" = "vie",
	"Polish" = "pol",
	"Javanese" = "jav",
	"Punjabi" = "pan",
	"Thai" = "tha",
	"Korean" = "kor"
}